var allResult = {
  mode: 'all',
  tests: [
    {
      number: '1a',
      name: 'simulate SGD',
      description: 'simulate SGD',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '1b',
      name: 'create small dataset',
      description: 'create small dataset',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '2a',
      name: 'loss',
      description: 'loss',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '2b',
      name: 'gradient',
      description: 'gradient',
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: '2c',
      name: 'smallest magnitude',
      description: 'smallest magnitude',
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: '3a-0-basic',
      name: 'basic test',
      description: 'basic test',
      max_seconds: 1,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3a-1-hidden',
      name: 'test multiple instances of the same word in a sentence',
      description: 'test multiple instances of the same word in a sentence',
      max_seconds: 1,
      max_points: 1,
      extra_credit: false,
      basic: false,
    },
    {
      number: '3b-0-basic',
      name:
        'basic sanity check for learning correct weights on two training and testing examples each',
      description:
        'basic sanity check for learning correct weights on two training and testing examples each',
      max_seconds: 1,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3b-1-basic',
      name:
        'test correct overriding of positive weight due to one negative instance with repeated words',
      description:
        'test correct overriding of positive weight due to one negative instance with repeated words',
      max_seconds: 2,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3b-2-basic',
      name: 'test classifier on real polarity dev dataset',
      description: 'test classifier on real polarity dev dataset',
      max_seconds: 16,
      max_points: 2,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3c-0-basic',
      name: 'test correct generation of small dataset labels',
      description: 'test correct generation of small dataset labels',
      max_seconds: 2,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3c-1-basic',
      name: 'test correct generation of large random dataset labels',
      description: 'test correct generation of large random dataset labels',
      max_seconds: 2,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3d',
      name: 'error analysis',
      description: 'error analysis',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '3e-0-basic',
      name: 'test basic character n-gram features',
      description: 'test basic character n-gram features',
      max_seconds: 1,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '3e-1-hidden',
      name: 'test feature extraction on repeated character n-grams',
      description: 'test feature extraction on repeated character n-grams',
      max_seconds: 2,
      max_points: 1,
      extra_credit: false,
      basic: false,
    },
    {
      number: '3f',
      name: 'explain value of n-grams',
      description: 'explain value of n-grams',
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4a',
      name: 'simulating 2-means',
      description: 'simulating 2-means',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4b-0-basic',
      name: 'test basic k-means on hardcoded datapoints',
      description: 'test basic k-means on hardcoded datapoints',
      max_seconds: 1,
      max_points: 1,
      extra_credit: false,
      basic: true,
    },
    {
      number: '4b-1-hidden',
      name: 'test stability of cluster assignments',
      description: 'test stability of cluster assignments',
      max_seconds: 4,
      max_points: 1,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4b-2-hidden',
      name: 'test stability of cluster locations',
      description: 'test stability of cluster locations',
      max_seconds: 4,
      max_points: 1,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4b-3-hidden',
      name: 'make sure the code runs fast enough',
      description: 'make sure the code runs fast enough',
      max_seconds: 5,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4c',
      name: 'handling same-cluster constraints',
      description: 'handling same-cluster constraints',
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4d',
      name: 'rerunning kmeans',
      description: 'rerunning kmeans',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: '4e',
      name: 'scaling kmeans',
      description: 'scaling kmeans',
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
  ],
  leaderboard: [],
};
